### ISSUE TITLE
Prepare GS 2.23-SNAPSHOT to test GeoFence WPS rules

### ISSUE THREAD

**Issue by etj** [GeoNode/geoserver-geonode-ext#146] opened 2023-02-14 11:40 UTC
We need a 2.22 version with [this PR](https://github.com/geoserver/geoserver/pull/6569) included -- so we need to build from [this branch](https://github.com/etj/geoserver/tree/GEOS-10682_2.22.x_geofence-wps).

Once the PR is stable, we'll be proposing the backport out from the WIP status.

We may want to build GeoServer directly, without using the POMs from this very project.
There's a initial investigation about the needed modules in [this document](https://docs.google.com/spreadsheets/d/1JT2fV249SdTc_4JCybYVvFdkwvI1C0pRHoRLEBi4INI/edit#gid=0)

**Comment by etj** [comment] 2023-02-14 11:41
Please note that the GS built this way will still have the `hibernate-spatial-h2` to be replaced.

**Comment by etj** [comment] 2023-02-14 12:16
We may want to try out GeoServer 2.23 (master, at the moment), so that the backport of the GeoFence improvements is not needed.

In this case we will make a release of GeoNode `4.1.something` just after GS `2.23.0` comes out.

**Comment by giohappy** [comment] 2023-02-15 11:43
@afabiani @etj as agreed in out last call the following will be done:

- test Geoserver 2.23.SNAPSHOT **built from the official** pom with GeoNode  This will give us a quick insight in what we miss from the current custom pom
- for the moment the foreseen problem will be the [gs-mapfish-print](https://github.com/GeoNode/geoserver-geonode-ext/blob/2.20.6/geoserver/pom.xml#L469-L483), where we exclude some dependencies that break Geoserver. For cases like this the proposal is to inflate the dependency inside the Dockerfile, as [we do](https://github.com/GeoNode/geonode-project/blob/master/docker/geoserver/Dockerfile#L35-L39) for `hibernate-spatial-postgis` and `postgis-jdbc`
- once the custom pom got out of the way, we can replace the task for the inclusion of the [data directory](https://github.com/GeoNode/geoserver-geonode-ext/tree/2.20.6/geoserver/data/geonode_v2206) inside the war with a script inside the Jenkins job

Regarding the replacement of jars performed inside the Dockerfile (second point above), what about moving this step inside the Jenkins Job? Is there any valid reason for doing it at that stage?

**Comment by afabiani** [comment] 2023-02-15 11:47
@giohappy we do this inside the Dockerfile because we are sure we can connect and confgiure GeoFence to a postgis DB. In the common use case GeoFence must be configured to store the rules on a local H2 store

**Comment by giohappy** [comment] 2023-02-15 11:48
>@giohappy we do this inside the Dockerfile because we are sure we can connect and confgiure GeoFence to a postgis DB. In the common use case GeoFence must be configured to store the rules on a local H2 store

Ok but we're building Geoserver for GeoNode, where we assume that we are using PostGIS. I don't see any context where this wouldn't be true.

**Comment by etj** [comment] 2023-02-15 11:48
@giohappy We may want the final war for installing GeoServer outside a dockerized environment (e.g. for development or for a clustered deployment)..

**Comment by etj** [comment] 2023-02-15 11:52
@giohappy it would be fine having it built by maven and deployed somewhere, so that it can also be used outside a dockerized environment (e.g. for developing)

**Comment by afabiani** [comment] 2023-02-16 16:16
As agreed with @etj we will modify the current GeoSolutions Jenkins build script in order to:

1. Build an updated https://artifacts.geonode.org/2.23.0/geonode-geoserver-ext-web-app-data.zip out of a dedicated repository
2. Build an updated https://artifacts.geonode.org/2.23.0/geoserver_vanilla.war out of a maven build including the official plugins
3. Build an updated https://artifacts.geonode.org/2.23.0/geoserver.war wich adds the following to the geoserver_vanilla.war
    a. The GeoNode base GEOSERVER_DATA_DIR
    b. The updated mapfish-print JARs from the GeoSolutions mapfish [print-lib](https://maven.geo-solutions.it/org/mapfish/print/print-lib/geosolutions-2.1-SNAPSHOT/print-lib-geosolutions-2.1-20220829.123515-4.jar)

NOTE: check if any other `JAR` is needed from the external repos.

**Comment by afabiani** [comment] 2023-02-20 16:21
@giohappy @etj  2.23.x artifacts ready:
 - https://artifacts.geonode.org/geoserver/2.23.x/geoserver.war
 - https://artifacts.geonode.org/geoserver/2.23.x/geoserver_vanilla.war
 - https://artifacts.geonode.org/geoserver/2.23.x/geonode-geoserver-ext-web-app-data.zip

**Comment by giohappy** [comment] 2023-02-20 16:34
nice @afabiani 
Once everything is confirmed to work we should:

- create releases / tags for the artifacts, so that Jenkins can pick the specific versioned files
- store the Jenkins'sjob configuration in this repo

**Comment by afabiani** [comment] 2023-02-20 17:02
@giohappy @etj FWI I had to manually add the following **missing** JARs to GeoServer in order to make it working. Other than this everything is working smoothly with GeoNode 4.1.x

https://github.com/GeoNode/geoserver-geonode-ext/tree/main/libs

**Comment by giohappy** [comment] 2023-02-24 16:01
For the moment I've only built the [Docker image for data 2.23.x](https://hub.docker.com/layers/geonode/geoserver_data/2.23.x/images/sha256-b044ccf6987abadbfbcd02c17e44eef739047df3c460dcc4ad06586488896f9f?context=repo), since it was needed to upgrade master and development demo.

The official image for GS 2.23.x will be built and uploaded once the tag has been cat in Geoserver.

**Closed** 2023-05-26 08:04 UTC
Labels: 2.23.0
